In [5]:
from sklearn.preprocessing import MinMaxScaler 
import numpy as np 

train_array=np.arange(0,11).reshape(-1,1)
train_array
test_array=np.arange(0,6).reshape(-1,1)
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
scaler=MinMaxScaler()

scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
train_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [11]:
scaler.fit(test_array)
test_scaled=scaler.transform(test_array)
test_scaled

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ]])

In [15]:
scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)

test_scaled=scaler.transform(test_array)

print('원본 test 데이터:',test_array)
print('scale test 데이터:',test_scaled)

원본 test 데이터: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
scale test 데이터: [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]]
