<a href="https://colab.research.google.com/github/Hyun-ho-Lee/python/blob/main/numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy의 기본 사용법 2021-06-09

In [1]:
import numpy as np

array=np.array([1,2,3])
print(array.size)
print(array.dtype)
print(array[2])

3
int64
3


In [3]:
array1=np.array(4)
print(array1)

#0으로 초기화 
array2 = np.zeros((4, 4), dtype=float)
print(array2)

#1로 초기화 
array3=np.ones((3,3),dtype=str)
print(array3)



4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [4]:
array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]
