<a href="https://colab.research.google.com/github/Hyun-ho-Lee/Python-Practice/blob/main/%EA%B8%B0%EB%B3%B8%EA%B8%B0_%EB%8B%A8%EB%A0%A8_08_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# String 

파이썬에서 문자열을 다루는법에 대해서 

In [50]:
x= 'Pluto is a planet'
y= 'Pluto is a planet'

x == y

True

In [51]:
print("Pluto's a planet!")
print('My dog is named "Pluto"')

Pluto's a planet!
My dog is named "Pluto"


In [52]:
#'' 사이에 ' 를 넣어주고 싶으면 \ 삽입 해서 처리해야함 ""같이 강조는 \" 이용
'Pluto\'s a plnanet!'

"Pluto's a plnanet!"

In [53]:
hello = "hello\nworld"
print(hello)

hello
world


In [54]:
# Indexing
planet = 'Pluto'
planet[0]

'P'

In [55]:
# Slicing
planet[-3:]

'uto'

In [56]:
len(planet)

5

In [57]:
[char+'! ' for char in planet]

['P! ', 'l! ', 'u! ', 't! ', 'o! ']

In [58]:
# ALL CAPS
claim = "Pluto is a planet!"
claim.upper()

'PLUTO IS A PLANET!'

In [59]:
claim.index('plan')

11

In [60]:
words = claim.split()
words

['Pluto', 'is', 'a', 'planet!']

In [61]:
datestr = '1956-01-31'
year, month, day = datestr.split('-')
print(year)
print(month)
print(day)

1956
01
31


In [62]:
' 👏 '.join([word.upper() for word in words])

'PLUTO 👏 IS 👏 A 👏 PLANET!'

In [63]:
planet + ', we miss you.'

'Pluto, we miss you.'

In [64]:
numbers = {'one':1, 'two':2, 'three':3}

In [65]:
numbers['one']

1

In [66]:
numbers['eleven'] = 11
numbers

{'eleven': 11, 'one': 1, 'three': 3, 'two': 2}

In [67]:
numbers['one'] = 'Pluto'
numbers

{'eleven': 11, 'one': 'Pluto', 'three': 3, 'two': 2}

In [68]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_to_initial = {planet: planet[0] for planet in planets}
planet_to_initial

{'Earth': 'E',
 'Jupiter': 'J',
 'Mars': 'M',
 'Mercury': 'M',
 'Neptune': 'N',
 'Saturn': 'S',
 'Uranus': 'U',
 'Venus': 'V'}

In [69]:
for k in numbers:
    print("{} = {}".format(k, numbers[k]))

one = Pluto
two = 2
three = 3
eleven = 11


In [70]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [71]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [72]:
print("pi to 4 signficant digits = {:.4}".format(math.pi))

pi to 4 signficant digits = 3.142


In [73]:
math.log(32,2)

5.0

In [74]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [75]:
import math as mt
mt.pi

3.141592653589793

In [76]:
import math 
mt = math

In [77]:
from math import *
print(pi,log(32,2))

3.141592653589793 5.0


In [78]:
from math import log, pi
from numpy import asarray

In [79]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [80]:
rolls = numpy.random.randint(low=1,high=6,size=10)
rolls

array([1, 1, 3, 4, 5, 2, 5, 3, 3, 3])

In [81]:
type(rolls)

numpy.ndarray

In [82]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [83]:
rolls.mean()

3.0

In [84]:
rolls.tolist()

[1, 1, 3, 4, 5, 2, 5, 3, 3, 3]

In [85]:
rolls + 10

array([11, 11, 13, 14, 15, 12, 15, 13, 13, 13])

In [86]:
rolls <= 3

array([ True,  True,  True, False, False,  True, False,  True,  True,
        True])

In [87]:
xlist = [[1,2,3],[2,4,6],]
x=numpy.asarray(xlist)
x

array([[1, 2, 3],
       [2, 4, 6]])

In [88]:
import numpy as np

In [89]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [90]:
arr.dtype

dtype('int64')

In [91]:
arr = np.array([1,2,3],dtype= float)
arr.dtype

dtype('float64')

In [92]:
a = np.array([1,2,3])
np.asarray(a) is a

True

In [93]:
def best_items(racers):
    """Given a list of racer dictionaries, return a dictionary mapping items to the number
    of times those items were picked up by racers who finished in first place.
    """
    winner_item_counts = {}
    for i in range(len(racers)):
        # The i'th racer dictionary
        racer = racers[i]
        # We're only interested in racers who finished in first
        if racer['finish'] == 1:
            for i in racer['items']:
                # Add one to the count for this item (adding it to the dict if necessary)
                if i not in winner_item_counts:
                    winner_item_counts[i] = 0
                winner_item_counts[i] += 1

        # Data quality issues :/ Print a warning about racers with no name set. We'll take care of it later.
        if racer['name'] is None:
            print("WARNING: Encountered racer with unknown name on iteration {}/{} (racer = {})".format(
                i+1, len(racers), racer['name'])
                 )
    return winner_item_counts

In [94]:
sample = [
    {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell',], 'finish': 3},
    {'name': 'Bowser', 'items': ['green shell',], 'finish': 1},
    {'name': None, 'items': ['mushroom',], 'finish': 2},
    {'name': 'Toad', 'items': ['green shell', 'mushroom'], 'finish': 1},
]
best_items(sample)

{'green shell': 2, 'mushroom': 1}

In [99]:
range(len(sample))

range(0, 4)

In [98]:
sample[0]

{'finish': 3,
 'items': ['green shell', 'banana', 'green shell'],
 'name': 'Peach'}

In [ ]:
def best_items(racers):
  winner_item_count = {}
  for i in range(len(racers)):
      racer = racers[i]
      #첫번쨰로 들어온 사람에게만 관심이있음
      if racer['finish'] == 1:
          for i in racer['items']:
              if i not in winner_item_counts:
                  winner_item_counts[i] =0
              winner_item_counts[i] += 1 
      if racer['name'] is None:
            print("WARNING: Encountered racer with unknown name on iteration {}/{} (racer = {})".format(
                i+1, len(racers), racer['name'])
                 )
    return winner_item_counts 